// Used for sqlite3 schema generation

Table accounts{
    id TEXT [pk,note:'UUID']
    type TEXT [notnull,note:'账户类型,i.e. 借记卡 信用卡']
    name TEXT [notnull,note:'账户名称,i.e 银行名称']
    card_number TEXT [note:'银行卡号']
    description TEXT [note:'账户描述']
    amount REAL [notnull,default:0.0,note:'账户余额']
    created_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'账户创建时间']
    updated_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'账户更新时间']
  }

Table transactions{
    id TEXT [pk,note:'UUID']
    type TEXT [notnull,note:'交易类型,i.e. 支出 收入 转账']
    src_account_id TEXT [notnull,note:'交易来源账户ID']
    dest_account_id TEXT [note:'交易目标账户ID'] // dest_account_id can be null for income and expense transactions
    amount REAL [notnull,note:'交易金额'] // positive for income, negative for expense. Always positive for transfer transactions, with the direction determined by src_account_id and dest_account_id
    description TEXT [note:'交易描述']
    category TEXT [notnull,note:'交易分类']
    tags TEXT [note:'交易标签, i.e. 意外开支. Must be a Json array of ids strings.']
    is_refund BOOLEAN [notnull,default: false,note:'是否为退款交易']
    related_transaction_id TEXT [note:'关联交易ID,用于标记退款交易的原始交易']
    created_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'交易创建时间']
    updated_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'交易更新时间']
    FOREIGN KEY (src_account_id) REFERENCES accounts(id)
    FOREIGN KEY (dest_account_id) REFERENCES accounts(id)
    FOREIGN KEY (related_transaction_id) REFERENCES transactions(id)
    FOREIGN KEY (category) REFERENCES categories(id)

}

Table categories{
    id TEXT [pk,note:'UUID']
    name TEXT [notnull,note:'分类名称,i.e. 餐饮 购物 娱乐']
    description TEXT [note:'分类描述']
    parent_category_id TEXT [note:'父分类ID,用于构建分类树结构.如果为空,则表示该分类为顶级分类']
    icon_color TEXT [notnull,default: '#ff0000',note:'分类图标颜色,使用HEX颜色值表示']
    icon_name TEXT [notnull,default: 'default_icon',note:'分类图标名称,用于前端显示分类图标']
    created_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'分类创建时间']
    updated_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'分类更新时间']
    FOREIGN KEY (parent_category_id) REFERENCES categories(id)
}

Table tags{
    id TEXT [pk,note:'UUID']
    name TEXT [notnull,note:'标签名称,i.e. 意外开支']
    description TEXT [note:'标签描述']
    color TEXT [notnull,default: '#ff0000',note:'标签颜色,使用HEX颜色值表示']
    created_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'标签创建时间']
    updated_at DATETIME [notnull,default: 'CURRENT_TIMESTAMP',note:'标签更新时间']
}
