export interface CategoryIconOption {
  label: string
  value: string
  icon: string
}

export const DEFAULT_CATEGORY_ICON = 'i-lucide-folder'

export const CATEGORY_ICON_ITEMS: CategoryIconOption[] = [
  { label: '餐具', value: 'i-lucide-utensils', icon: 'i-lucide-utensils' },
  { label: '咖啡', value: 'i-lucide-coffee', icon: 'i-lucide-coffee' },
  { label: '三明治', value: 'i-lucide-sandwich', icon: 'i-lucide-sandwich' },
  { label: '蛋糕', value: 'i-lucide-cake-slice', icon: 'i-lucide-cake-slice' },
  { label: '烹饪', value: 'i-lucide-cooking-pot', icon: 'i-lucide-cooking-pot' },
  { label: '饮品', value: 'i-lucide-wine', icon: 'i-lucide-wine' },
  { label: '汽车', value: 'i-lucide-car-front', icon: 'i-lucide-car-front' },
  { label: '公交', value: 'i-lucide-bus-front', icon: 'i-lucide-bus-front' },
  { label: '火车', value: 'i-lucide-train-front', icon: 'i-lucide-train-front' },
  { label: '自行车', value: 'i-lucide-bike', icon: 'i-lucide-bike' },
  { label: '飞机', value: 'i-lucide-plane', icon: 'i-lucide-plane' },
  { label: '加油', value: 'i-lucide-fuel', icon: 'i-lucide-fuel' },
  { label: '住宅', value: 'i-lucide-house', icon: 'i-lucide-house' },
  { label: '建筑', value: 'i-lucide-building-2', icon: 'i-lucide-building-2' },
  { label: '钥匙', value: 'i-lucide-key-round', icon: 'i-lucide-key-round' },
  { label: '沙发', value: 'i-lucide-sofa', icon: 'i-lucide-sofa' },
  { label: '吊灯', value: 'i-lucide-lamp-ceiling', icon: 'i-lucide-lamp-ceiling' },
  { label: '购物袋', value: 'i-lucide-shopping-bag', icon: 'i-lucide-shopping-bag' },
  { label: '购物车', value: 'i-lucide-shopping-cart', icon: 'i-lucide-shopping-cart' },
  { label: '服饰', value: 'i-lucide-shirt', icon: 'i-lucide-shirt' },
  { label: '礼物', value: 'i-lucide-gift', icon: 'i-lucide-gift' },
  { label: '手机', value: 'i-lucide-smartphone', icon: 'i-lucide-smartphone' },
  { label: '耳机', value: 'i-lucide-headphones', icon: 'i-lucide-headphones' },
  { label: '游戏', value: 'i-lucide-gamepad-2', icon: 'i-lucide-gamepad-2' },
  { label: '电影', value: 'i-lucide-film', icon: 'i-lucide-film' },
  { label: '音乐', value: 'i-lucide-music-2', icon: 'i-lucide-music-2' },
  { label: '运动', value: 'i-lucide-dumbbell', icon: 'i-lucide-dumbbell' },
  { label: '心脏健康', value: 'i-lucide-heart-pulse', icon: 'i-lucide-heart-pulse' },
  { label: '药品', value: 'i-lucide-pill', icon: 'i-lucide-pill' },
  { label: '医疗', value: 'i-lucide-stethoscope', icon: 'i-lucide-stethoscope' },
  { label: '医院', value: 'i-lucide-hospital', icon: 'i-lucide-hospital' },
  { label: '毕业', value: 'i-lucide-graduation-cap', icon: 'i-lucide-graduation-cap' },
  { label: '书本', value: 'i-lucide-book-open', icon: 'i-lucide-book-open' },
  { label: '图书馆', value: 'i-lucide-library', icon: 'i-lucide-library' },
  { label: '工作', value: 'i-lucide-briefcase-business', icon: 'i-lucide-briefcase-business' },
  { label: '钱包', value: 'i-lucide-wallet-cards', icon: 'i-lucide-wallet-cards' },
  { label: '钞票', value: 'i-lucide-banknote', icon: 'i-lucide-banknote' },
  { label: '收入', value: 'i-lucide-badge-dollar-sign', icon: 'i-lucide-badge-dollar-sign' },
  { label: '硬币', value: 'i-lucide-coins', icon: 'i-lucide-coins' },
  { label: '趋势', value: 'i-lucide-chart-no-axes-combined', icon: 'i-lucide-chart-no-axes-combined' },
  { label: '收据', value: 'i-lucide-receipt-text', icon: 'i-lucide-receipt-text' },
  { label: '包裹', value: 'i-lucide-package', icon: 'i-lucide-package' },
  { label: '宠物', value: 'i-lucide-paw-print', icon: 'i-lucide-paw-print' },
  { label: '育儿', value: 'i-lucide-baby', icon: 'i-lucide-baby' },
  { label: '工具', value: 'i-lucide-wrench', icon: 'i-lucide-wrench' },
  { label: '维修', value: 'i-lucide-hammer', icon: 'i-lucide-hammer' },
  { label: '能量', value: 'i-lucide-zap', icon: 'i-lucide-zap' },
  { label: '灵感', value: 'i-lucide-lightbulb', icon: 'i-lucide-lightbulb' },
  { label: '出行与网络', value: 'i-lucide-earth', icon: 'i-lucide-earth' },
  { label: '日历', value: 'i-lucide-calendar-days', icon: 'i-lucide-calendar-days' },
]
