import { expect, test } from '@playwright/test'

for (const viewport of [{ width: 1440, height: 900 }, { width: 375, height: 812 }]) {
  test(`分类浮层 ${viewport.width}×${viewport.height}：原位选择、导航、焦点与背景保持`, async ({ page }, testInfo) => {
    await page.setViewportSize(viewport)
    const suffix = `${viewport.width}-${Date.now()}`
    const create = async (path: string, data: object) => {
      const response = await page.request.post(`http://127.0.0.1:8012/api/v1/${path}`, { data })
      expect(response.ok(), await response.text()).toBe(true)
      return response.json() as Promise<{ id: string; name: string }>
    }
    const root = await create('categories', { name: `餐饮示例-${suffix}`, purpose: 'expense', iconName: 'i-lucide-utensils', iconColor: '#C73E3A' })
    const child = await create('categories', { name: `午餐示例-${suffix}`, purpose: 'expense', parentCategoryId: root.id, iconName: 'i-lucide-utensils', iconColor: '#C73E3A' })
    const leaf = await create('categories', { name: `工作餐-${suffix}`, purpose: 'expense', parentCategoryId: child.id, iconName: 'i-lucide-coffee', iconColor: '#005CAF' })
    const sibling = await create('categories', { name: `晚餐-${suffix}`, purpose: 'expense', parentCategoryId: root.id, iconName: 'i-lucide-utensils', iconColor: '#C73E3A' })
    for (let index = 0; index < 12; index++) await create('categories', { name: `长名称示例-${suffix}-${index}-${'分类名称'.repeat(3)}`, purpose: 'expense', parentCategoryId: root.id, iconName: 'i-lucide-utensils', iconColor: '#C73E3A' })
    await page.goto('/transactions')
    await page.waitForFunction(() => Boolean((document.querySelector('#__nuxt') as HTMLElement & { __vue_app__?: unknown } | null)?.__vue_app__))
    await page.getByRole('button', { name: '记一笔', exact: true }).first().click()
    const editor = page.getByRole('dialog', { name: '交易表单', exact: true, includeHidden: true })
    const trigger = editor.getByRole('button', { name: `${root.name}，查看子分类`, includeHidden: true })
    await trigger.scrollIntoViewIfNeeded()
    const background = editor.locator('.modal-editor-body')
    const before = await background.evaluate(element => ({ scroll: element.scrollTop, tiles: element.querySelectorAll('[data-category-tile]').length }))
    await page.screenshot({ path: testInfo.outputPath('main-form.png') })
    await trigger.click()
    const modal = page.getByRole('dialog').filter({ has: page.locator('.transaction-category-panel') })
    const childButton = modal.getByRole('button', { name: `${child.name}，查看子分类` })
    await expect(modal.locator('[data-category-tile]').first()).toBeFocused()
    await expect(modal).toHaveAccessibleName(root.name)
    expect(await background.evaluate(element => ({ scroll: element.scrollTop, tiles: element.querySelectorAll('[data-category-tile]').length }))).toEqual(before)
    await expect(editor.getByRole('button', { name: '完成', includeHidden: true })).not.toBeFocused()
    await page.screenshot({ path: testInfo.outputPath('category-open.png') })
    await childButton.focus()
    await childButton.press('Enter')
    const leafButton = modal.getByRole('button', { name: `${leaf.name}，选择分类` })
    await expect(leafButton).toBeFocused()
    await leafButton.press('Space')
    await expect(leafButton).toHaveAttribute('aria-pressed', 'true')
    await expect(leafButton).toBeFocused()
    await expect(modal.getByRole('status')).toContainText(`${root.name} / ${child.name} / ${leaf.name}`)
    await leafButton.press('Space')
    await expect(leafButton).toHaveAttribute('aria-pressed', 'true')
    await page.screenshot({ path: testInfo.outputPath('category-selected.png') })
    await modal.getByRole('button', { name: '关闭分类选择' }).click()
    await expect(trigger).toBeFocused()
    await trigger.click()
    await expect(modal).toHaveAccessibleName(child.name)
    await expect(leafButton).toBeFocused()
    // Tab 始终留在顶层分类弹窗，背景表单不可获得焦点。
    for (let index = 0; index < 12; index++) {
      await page.keyboard.press('Tab')
      expect(await modal.evaluate(element => element.contains(document.activeElement))).toBe(true)
    }
    await page.keyboard.press('Escape')
    await expect(modal).toHaveAccessibleName(root.name)
    await expect(childButton).toBeFocused()
    await childButton.press('Enter')
    await modal.getByLabel('分类层级').getByRole('button', { name: root.name, exact: true }).click()
    await expect(childButton).toBeFocused()
    await childButton.click()
    await modal.getByRole('button', { name: '返回上级' }).click()
    await expect(childButton).toBeFocused()
    const siblingButton = modal.getByRole('button', { name: `${sibling.name}，选择分类` })
    await siblingButton.click()
    await expect(siblingButton).toHaveAttribute('aria-pressed', 'true')
    await expect(siblingButton).toBeFocused()
    await modal.getByRole('button', { name: `选择当前分类：${root.name}` }).click()
    const currentButton = modal.getByRole('button', { name: `选择当前分类：${root.name}` })
    await expect(currentButton).toHaveAttribute('aria-pressed', 'true')
    await expect(currentButton).toBeFocused()
    await modal.getByRole('button', { name: '关闭分类选择' }).click()
    await trigger.click()
    await expect(currentButton).toBeFocused()
    await siblingButton.click()
    await modal.getByRole('button', { name: '关闭分类选择' }).click()
    await expect(modal).toBeHidden()
    await expect(trigger).toBeFocused()
    await expect(trigger).toContainText(`已选：${sibling.name}`)
    await expect(editor).toContainText(`已选择：${root.name} / ${sibling.name}`)
    await trigger.click()
    await expect(siblingButton).toBeFocused()
    const bounds = await modal.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(15)
    expect(bounds!.y).toBeGreaterThanOrEqual(15)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width - 15)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height - 15)
    expect(await modal.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    const modalScroll = modal.locator('[data-slot="body"]')
    if (viewport.width === 375) expect(await modalScroll.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
    await modalScroll.evaluate(element => { element.scrollTop = element.scrollHeight })
    await modal.getByRole('button', { name: '关闭分类选择' }).click()
    await expect(trigger).toBeFocused()
    await trigger.click()
    // 点击遮罩只关闭分类弹窗，保留选择及外层记账表单。
    await page.mouse.click(3, 3)
    await expect(modal).toBeHidden()
    await expect(editor).toBeVisible()
    await expect(trigger).toBeFocused()
    await trigger.click()
    await page.keyboard.press('Escape')
    await expect(modal).toBeHidden()
    await expect(editor).toBeVisible()
    await expect(trigger).toBeFocused()
    await editor.getByRole('radio', { name: '收入', exact: true }).click()
    await expect(editor.locator('.transaction-category-selection')).toHaveCount(0)
    await editor.getByRole('radio', { name: '支出', exact: true }).click()
    await trigger.click()
    await expect(modal.locator('[data-category-tile]').first()).toBeFocused()
    await expect(modal.getByRole('status')).toHaveCount(0)
  })
}

test('分类浮层：异步资源刷新回退到有效层，保存期间禁用，编辑定位已选分类', async ({ page }) => {
  const suffix = Date.now().toString()
  const create = async (path: string, data: object) => {
    const response = await page.request.post(`http://127.0.0.1:8012/api/v1/${path}`, { data })
    expect(response.ok(), await response.text()).toBe(true)
    return response.json() as Promise<{ id: string; name: string }>
  }
  const account = await create('accounts', { name: `浮层账户-${suffix}`, type: 'debit' })
  await create('transactions', { type: 'balance_adjustment', sourceAccountId: account.id, amount: 1000, balanceAdjustmentDirection: 'increase', occurredAt: new Date().toISOString() })
  const root = await create('categories', { name: `刷新父级-${suffix}`, purpose: 'expense' })
  const child = await create('categories', { name: `刷新中级-${suffix}`, purpose: 'expense', parentCategoryId: root.id })
  const leaf = await create('categories', { name: `刷新末级-${suffix}`, purpose: 'expense', parentCategoryId: child.id })
  const sibling = await create('categories', { name: `刷新同级-${suffix}`, purpose: 'expense', parentCategoryId: root.id })
  await page.goto('/transactions')
  await page.waitForFunction(() => Boolean((document.querySelector('#__nuxt') as HTMLElement & { __vue_app__?: unknown } | null)?.__vue_app__))
  await page.getByRole('button', { name: '记一笔', exact: true }).first().click()
  const editor = page.getByRole('dialog', { name: '交易表单', exact: true, includeHidden: true })
  const trigger = editor.getByRole('button', { name: `${root.name}，查看子分类`, includeHidden: true })
  const modal = page.getByRole('dialog').filter({ has: page.locator('.transaction-category-panel') })
  await trigger.click()
  await modal.getByRole('button', { name: `${child.name}，查看子分类` }).click()
  await modal.getByRole('button', { name: `${leaf.name}，选择分类` }).click()
  await modal.getByRole('button', { name: '关闭分类选择' }).click()
  let releaseRefresh!: () => void
  let refreshStarted!: () => void
  const started = new Promise<void>(resolve => { refreshStarted = resolve })
  const gate = new Promise<void>(resolve => { releaseRefresh = resolve })
  await page.route('**/api/v1/categories', async route => {
    const response = await route.fetch()
    refreshStarted()
    await gate
    const categories = await response.json() as Array<{ id: string; name: string }>
    await route.fulfill({ json: categories.filter(item => item.id !== child.id && item.id !== leaf.id).map(item => item.id === root.id ? { ...item, name: `刷新父级新版-${suffix}` } : item) })
  })
  // 模拟分类弹窗打开前已开始、打开后才完成的资源同步。
  await page.getByRole('button', { name: '刷新', exact: true, includeHidden: true }).evaluate(element => (element as HTMLButtonElement).click())
  await started
  await trigger.click()
  await expect(modal).toHaveAccessibleName(child.name)
  releaseRefresh()
  await expect(modal).toHaveAccessibleName(`刷新父级新版-${suffix}`)
  await expect(modal.getByRole('button', { name: `${sibling.name}，选择分类` })).toBeFocused()
  await expect(modal.getByRole('button', { name: `${leaf.name}，选择分类` })).toHaveCount(0)
  await modal.getByRole('button', { name: `${sibling.name}，选择分类` }).click()
  await modal.getByRole('button', { name: '关闭分类选择' }).click()
  await page.unroute('**/api/v1/categories')
  await editor.getByLabel('账户', { exact: true }).click()
  await page.getByRole('option', { name: `${account.name} · ¥1,000.00`, exact: true }).click()
  await editor.getByLabel('金额（元）', { exact: true }).fill('12')
  await editor.getByLabel('说明', { exact: true }).fill(`浮层编辑定位-${suffix}`)
  let releaseSave!: () => void
  const saveGate = new Promise<void>(resolve => { releaseSave = resolve })
  await page.route('**/api/v1/transactions', async route => {
    if (route.request().method() !== 'POST') { await route.continue(); return }
    expect(route.request().postDataJSON()).toMatchObject({ categoryId: sibling.id, amount: 12 })
    await saveGate
    await route.continue()
  })
  await editor.getByRole('button', { name: '保存再记', exact: true }).click()
  await expect(editor.locator('[data-category-tile]').first()).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(editor).toBeVisible()
  releaseSave()
  await expect(editor.getByLabel('金额（元）', { exact: true })).toHaveValue('')
  await expect(editor).toContainText(`${root.name} / ${sibling.name}`)
  await editor.getByRole('button', { name: `${root.name}，查看子分类` }).click()
  await expect(modal.getByRole('button', { name: `${sibling.name}，选择分类` })).toBeFocused()
  await modal.getByRole('button', { name: '关闭分类选择' }).click()
  await editor.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByLabel('搜索交易', { exact: true }).fill(`浮层编辑定位-${suffix}`)
  await page.getByRole('button').filter({ hasText: `浮层编辑定位-${suffix}` }).click()
  await page.getByRole('button', { name: '编辑交易', exact: true }).click()
  await editor.getByRole('button', { name: `${root.name}，查看子分类` }).click()
  await expect(modal.getByRole('button', { name: `${sibling.name}，选择分类` })).toHaveAttribute('aria-pressed', 'true')
  await expect(modal.getByRole('button', { name: `${sibling.name}，选择分类` })).toBeFocused()
})
