import { test, expect } from '@playwright/test'

test('真实账本：资源、收支、转账、调账、退款、作废和持久化', async ({ page }) => {
  const suffix = Date.now().toString()
  const wallet = `钱包${suffix}`, bank = `银行${suffix}`, expense = `餐饮${suffix}`, income = `工资${suffix}`, tag = `日常${suffix}`
  const errors: string[] = []
  const apiRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().includes('/api/v1/')) apiRequests.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('button', { name: '记一笔', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '账户', exact: true }).click()
  for (const name of [wallet, bank]) {
    await page.getByRole('button', { name: '新建账户', exact: true }).click()
    await page.getByLabel('名称', { exact: true }).fill(name)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(name, { exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: '分类与标签', exact: true }).click()
  for (const [name, purpose] of [[expense, 'expense'], [income, 'income']]) {
    await page.getByRole('button', { name: '新建分类', exact: true }).click()
    await page.getByLabel('名称', { exact: true }).fill(name!)
    await page.getByRole('combobox', { name: '用途', exact: true }).selectOption(purpose!)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(name!, { exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: '新建标签', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill(tag)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText(tag, { exact: true })).toBeVisible()
  async function create(kind: string, amount: string, description: string) {
    await page.getByRole('button', { name: '记一笔', exact: true }).click()
    await page.getByRole('combobox', { name: '交易类型', exact: true }).selectOption(kind)
    await page.getByLabel('金额（元）', { exact: true }).fill(amount)
    await page.getByLabel('说明', { exact: true }).fill(description)
    if (kind === 'income') {
      await page.getByRole('combobox', { name: '收款账户', exact: true }).selectOption({ label: wallet })
      await page.getByRole('combobox', { name: '分类', exact: true }).selectOption({ label: income })
    } else if (kind === 'transfer') {
      await page.getByRole('combobox', { name: '转出账户', exact: true }).selectOption({ label: `${wallet} · ¥1,030.00` })
      await page.getByRole('combobox', { name: '转入账户', exact: true }).selectOption({ label: bank })
    } else {
      const option = await page.getByRole('combobox', { name: '账户', exact: true }).locator('option').allTextContents()
      await page.getByRole('combobox', { name: '账户', exact: true }).selectOption({ label: option.find(v => v.startsWith(wallet))! })
      if (kind === 'expense') await page.getByRole('combobox', { name: '分类', exact: true }).selectOption({ label: expense })
    }
    if (kind === 'expense') await page.getByLabel(tag, { exact: true }).check()
    await page.getByRole('button', { name: '保存交易', exact: true }).click()
    await expect(page.getByRole('button', { name: '保存交易', exact: true })).toBeHidden()
  }
  await create('balance_adjustment', '1000', `期初${suffix}`)
  await create('income', '100', `收入${suffix}`)
  await create('expense', '80', `午餐${suffix}`)
  await page.getByRole('button', { name: '交易', exact: true }).click()
  await page.getByLabel('搜索交易').fill(`午餐${suffix}`)
  await page.getByRole('button').filter({ hasText: `午餐${suffix}` }).click()
  await page.getByRole('button', { name: '编辑交易', exact: true }).click()
  await page.getByLabel('金额（元）', { exact: true }).fill('70')
  await page.getByRole('button', { name: '保存交易', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存交易', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '申请退款', exact: true }).click()
  await page.getByLabel('金额（元）', { exact: true }).fill('71')
  await page.getByRole('button', { name: '保存交易', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('退款不能超过')
  await page.getByLabel('金额（元）', { exact: true }).fill('20')
  await page.getByLabel('说明', { exact: true }).fill(`退款${suffix}`)
  await page.getByRole('button', { name: '保存交易', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存交易', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '作废交易', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('退款')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.getByLabel('搜索交易').fill(`退款${suffix}`)
  await page.getByRole('button').filter({ hasText: `退款${suffix}` }).click()
  await page.getByRole('button', { name: '作废交易', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByText('已作废', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await create('transfer', '100', `转账${suffix}`)
  await page.getByRole('button', { name: '统计分析', exact: true }).click()
  await expect(page.getByText('普通收入', { exact: true })).toBeVisible()
  await expect(page.locator('.category-stat').filter({ hasText: expense })).toContainText('¥70.00')
  await page.locator('.category-stat').filter({ hasText: expense }).click()
  await expect(page.locator('.drill-panel')).toContainText('净支出 ¥70.00')
  expect(apiRequests.some(url => url.includes('/statistics/overview'))).toBe(true)
  expect(apiRequests.some(url => url.includes('/statistics/expense-transactions'))).toBe(true)
  expect(apiRequests.some(url => url.includes('/transactions?page=1&pageSize=20'))).toBe(true)
  expect(apiRequests.some(url => url.includes('includeVoided'))).toBe(false)
  await page.getByRole('button', { name: '账户', exact: true }).click()
  await expect(page.locator('.balance-card').filter({ hasText: wallet })).toContainText('¥930.00')
  await expect(page.locator('.balance-card').filter({ hasText: bank })).toContainText('¥100.00')
  await page.reload()
  await expect(page.getByRole('button', { name: '记一笔', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '账户', exact: true }).click()
  await expect(page.locator('.balance-card').filter({ hasText: wallet })).toContainText('¥930.00')
  await page.locator('.balance-card').filter({ hasText: wallet }).getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '分类与标签', exact: true }).click()
  await expect(page.getByRole('button', { name: '新建分类', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await page.screenshot({ path: 'test-results/mvp-mobile.png', fullPage: true })
})

test('资源维护、子树移动确认、错误保留输入与服务恢复', async ({ page }) => {
  const suffix = Date.now().toString()
  await page.goto('/')
  await expect(page.getByRole('button', { name: '记一笔', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '分类与标签', exact: true }).click()
  for (const name of [`父A${suffix}`, `父B${suffix}`, `子${suffix}`]) {
    await page.getByRole('button', { name: '新建分类', exact: true }).click()
    await page.getByLabel('名称', { exact: true }).fill(name)
    if (name.startsWith('子')) await page.getByLabel('父分类').selectOption({ label: `父A${suffix}` })
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(name, { exact: true })).toBeVisible()
  }
  const child = page.locator('.resource-row').filter({ has: page.getByText(`子${suffix}`, { exact: true }) })
  await child.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByLabel('父分类').selectOption({ label: `父B${suffix}` })
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请确认移动分类')
  await page.getByLabel('确认将此分类及其所有子分类一起移动').check()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(child).toContainText(`上级：父B${suffix}`)
  await page.getByRole('button', { name: '新建分类', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill(`子${suffix}`)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue(`子${suffix}`)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await child.getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(child).toHaveCount(0)
  for (const name of [`父A${suffix}`, `父B${suffix}`]) {
    await page.locator('.resource-row').filter({ has: page.getByText(name, { exact: true }) }).getByRole('button', { name: '删除', exact: true }).click()
    await page.getByRole('button', { name: '确认操作', exact: true }).click()
    await expect(page.getByText(name, { exact: true })).toBeHidden()
  }
  await page.route('**/api/v1/accounts', route => route.abort())
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('无法连接')
  await page.unroute('**/api/v1/accounts')
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.getByRole('alert')).toBeHidden()
  await page.getByRole('button', { name: '总览', exact: true }).click()
  await page.screenshot({ path: 'test-results/mvp-desktop.png', fullPage: true })
})
