import { test, expect, type Page } from '@playwright/test'

async function selectNuxtUiOption(page: Page, label: string, option: string) {
  await page.getByRole('dialog').last().getByLabel(label, { exact: true }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}

test('真实账本：资源、收支、转账、调账、退款、作废和持久化', async ({ page }) => {
  const suffix = Date.now().toString()
  const wallet = `钱包${suffix}`, bank = `银行${suffix}`, expense = `餐饮${suffix}`, income = `工资${suffix}`, tag = `日常${suffix}`
  const errors: string[] = []
  const apiRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (request.url().includes('/api/v1/')) apiRequests.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('button', { name: '记一笔', exact: true })).toBeEnabled()
  await page.getByRole('link', { name: '账户', exact: true }).click()
  for (const name of [wallet, bank]) {
    await page.getByRole('button', { name: '新建账户', exact: true }).click()
    await page.getByLabel('名称', { exact: true }).fill(name)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(name, { exact: true })).toBeVisible()
  }
  const bankCard = page.locator('[data-account-id]').filter({ hasText: bank })
  await bankCard.getByRole('button', { name: '调账', exact: true }).click()
  await expect(page.getByRole('dialog').last()).toContainText('调账')
  await page.getByRole('dialog').last().getByRole('button', { name: '关闭', exact: true }).click()
  await bankCard.getByRole('button', { name: `更多操作：${bank}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '编辑', exact: true }).click()
  await page.getByLabel('说明', { exact: true }).fill('工资卡')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(bankCard).toContainText('工资卡')

  const disposable = `临时账户${suffix}`
  await page.getByRole('button', { name: '新建账户', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill(disposable)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const disposableCard = page.locator('[data-account-id]').filter({ hasText: disposable })
  await disposableCard.getByRole('button', { name: `更多操作：${disposable}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await expect(page.getByRole('button', { name: '取消', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(disposableCard).toHaveCount(0)

  await page.getByRole('link', { name: '分类与标签', exact: true }).click()
  for (const [name, purpose] of [[expense, 'expense'], [income, 'income']]) {
    await page.getByRole('tab', { name: purpose === 'income' ? /收入分类/ : /支出分类/ }).click()
    await page.getByRole('button', { name: '新建分类', exact: true }).click()
    await page.getByLabel('名称', { exact: true }).fill(name!)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(name!, { exact: true })).toBeVisible()
  }
  await page.getByRole('tab', { name: /标签/ }).click()
  await page.getByRole('button', { name: '新建标签', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill(tag)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText(tag, { exact: true })).toBeVisible()
  async function create(kind: string, amount: string, description: string) {
    await page.getByRole('button', { name: '记一笔', exact: true }).click()
    const kindLabels: Record<string, string> = { expense: '支出', income: '收入', transfer: '转账', balance_adjustment: '调账' }
    await selectNuxtUiOption(page, '交易类型', kindLabels[kind]!)
    await page.getByLabel('金额（元）', { exact: true }).fill(amount)
    await page.getByLabel('说明', { exact: true }).fill(description)
    if (kind === 'income') {
      await selectNuxtUiOption(page, '收款账户', wallet)
      await selectNuxtUiOption(page, '分类', income)
    } else if (kind === 'transfer') {
      await selectNuxtUiOption(page, '转出账户', `${wallet} · ¥1,030.00`)
      await selectNuxtUiOption(page, '转入账户', bank)
    } else {
      await page.getByRole('dialog').last().getByLabel('账户', { exact: true }).click()
      const options = await page.getByRole('option').allTextContents()
      await page.getByRole('option', { name: options.find(value => value.startsWith(wallet))!, exact: true }).click()
      if (kind === 'expense') await selectNuxtUiOption(page, '分类', expense)
    }
    if (kind === 'expense') await page.getByLabel(tag, { exact: true }).check()
    await page.getByRole('button', { name: '保存交易', exact: true }).click()
    await expect(page.getByRole('button', { name: '保存交易', exact: true })).toBeHidden()
  }
  await create('balance_adjustment', '1000', `期初${suffix}`)
  await create('income', '100', `收入${suffix}`)
  await create('expense', '80', `午餐${suffix}`)
  await page.getByRole('link', { name: '交易', exact: true }).click()
  await page.getByLabel('搜索交易').fill(`午餐${suffix}`)
  await page.getByRole('button').filter({ hasText: `午餐${suffix}` }).click()
  await page.getByRole('button', { name: '编辑交易', exact: true }).click()
  await page.getByLabel('金额（元）', { exact: true }).fill('70')
  await page.getByRole('button', { name: '保存交易', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存交易', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '申请退款', exact: true }).click()
  await page.getByLabel('金额（元）', { exact: true }).fill('71')
  await page.getByRole('button', { name: '保存交易', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('退款不能超过')
  await page.getByLabel('金额（元）', { exact: true }).fill('20')
  await page.getByLabel('说明', { exact: true }).fill(`退款${suffix}`)
  await page.getByRole('button', { name: '保存交易', exact: true }).click()
  await expect(page.getByRole('button', { name: '保存交易', exact: true })).toBeHidden()
  await page.getByRole('button', { name: '作废交易', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('退款')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '关闭交易详情', exact: true }).click()
  await page.getByLabel('搜索交易').fill(`退款${suffix}`)
  await page.getByRole('button').filter({ hasText: `退款${suffix}` }).click()
  await page.getByRole('button', { name: '作废交易', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByText('已作废', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭交易详情', exact: true }).click()
  await create('transfer', '100', `转账${suffix}`)
  await page.getByRole('link', { name: '统计分析', exact: true }).click()
  await expect(page.getByText('普通收入', { exact: true })).toBeVisible()
  await expect(page.locator('.category-stat').filter({ hasText: expense })).toContainText('¥70.00')
  await page.locator('.category-stat').filter({ hasText: expense }).click()
  await expect(page.locator('.drill-panel')).toContainText('净支出 ¥70.00')
  expect(apiRequests.some(url => url.includes('/statistics/overview'))).toBe(true)
  expect(apiRequests.some(url => url.includes('/statistics/expense-transactions'))).toBe(true)
  expect(apiRequests.some(url => url.includes('/transactions?page=1&pageSize=20'))).toBe(true)
  expect(apiRequests.some(url => url.includes('includeVoided'))).toBe(false)
  await page.getByRole('link', { name: '账户', exact: true }).click()
  await expect(page.locator('[data-account-id]').filter({ hasText: wallet })).toContainText('¥930.00')
  await expect(page.locator('[data-account-id]').filter({ hasText: bank })).toContainText('¥100.00')
  await page.reload()
  await expect(page.getByRole('button', { name: '记一笔', exact: true })).toBeEnabled()
  await page.getByRole('link', { name: '账户', exact: true }).click()
  const walletCard = page.locator('[data-account-id]').filter({ hasText: wallet })
  await expect(walletCard).toContainText('¥930.00')
  await walletCard.getByRole('button', { name: `更多操作：${wallet}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '打开主导航', exact: true }).click()
  await page.getByRole('dialog', { name: '主导航' }).getByRole('link', { name: '分类与标签', exact: true }).click()
  await expect(page.getByRole('button', { name: '新建分类', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await page.screenshot({ path: 'test-results/mvp-mobile.png', fullPage: true })
})

test('资源维护、子树移动确认、错误保留输入与服务恢复', async ({ page }) => {
  const suffix = Date.now().toString()
  await page.goto('/')
  await expect(page.getByRole('button', { name: '记一笔', exact: true })).toBeEnabled()
  await page.getByRole('link', { name: '分类与标签', exact: true }).click()
  for (const name of [`父A${suffix}`, `父B${suffix}`, `子${suffix}`]) {
    await page.getByRole('button', { name: '新建分类', exact: true }).click()
    await page.getByLabel('名称', { exact: true }).fill(name)
    if (name.startsWith('子')) await selectNuxtUiOption(page, '父分类', `父A${suffix}`)
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByText(name, { exact: true })).toBeVisible()
  }
  const child = page.locator('[data-category-row-id]').filter({ has: page.getByText(`子${suffix}`, { exact: true }) })
  await child.getByRole('button', { name: `更多操作：子${suffix}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '编辑', exact: true }).click()
  await selectNuxtUiOption(page, '父分类', `父B${suffix}`)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('请确认移动分类')
  await page.getByLabel('确认将此分类及其所有子分类一起移动').check()
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(child).toContainText(`上级：父B${suffix}`)
  await page.getByRole('button', { name: '新建分类', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill(`子${suffix}`)
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue(`子${suffix}`)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await child.getByRole('button', { name: `更多操作：子${suffix}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(child).toHaveCount(0)
  for (const name of [`父A${suffix}`, `父B${suffix}`]) {
    const row = page.locator('[data-category-row-id]').filter({ has: page.getByText(name, { exact: true }) })
    await row.getByRole('button', { name: `更多操作：${name}`, exact: true }).click()
    await page.getByRole('menuitem', { name: '删除', exact: true }).click()
    await page.getByRole('button', { name: '确认操作', exact: true }).click()
    await expect(page.getByText(name, { exact: true })).toBeHidden()
  }
  await page.route('**/api/v1/accounts', route => route.abort())
  await page.getByRole('button', { name: '刷新', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('无法连接')
  await page.unroute('**/api/v1/accounts')
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.getByRole('alert')).toBeHidden()
  await page.getByRole('link', { name: '总览', exact: true }).click()
  await page.screenshot({ path: 'test-results/mvp-desktop.png', fullPage: true })
})

test('分类树：三层层级、展开搜索、键盘导航与删除冲突', async ({ page }) => {
  const suffix = Date.now().toString()
  const names = { root: `树根${suffix}`, child: `树枝${suffix}`, leaf: `树叶${suffix}` }
  const api = 'http://127.0.0.1:8012/api/v1/categories'
  const create = async (name: string, parentCategoryId?: string) => {
    const response = await page.request.post(api, { data: { name, purpose: 'expense', parentCategoryId: parentCategoryId || null, iconColor: '#005CAF', iconName: 'i-lucide-folder' } })
    expect(response.ok()).toBe(true)
    return response.json() as Promise<{ id: string }>
  }
  const root = await create(names.root)
  const child = await create(names.child, root.id)
  await create(names.leaf, child.id)
  await page.goto('/')
  await page.getByRole('link', { name: '分类与标签', exact: true }).click()
  const tree = page.getByRole('tree', { name: '支出分类树' })
  const rootItem = tree.getByRole('treeitem', { name: new RegExp(names.root) })
  const childItem = tree.getByRole('treeitem', { name: new RegExp(names.child) })
  const leafItem = tree.getByRole('treeitem', { name: new RegExp(names.leaf) })
  await expect(rootItem).toHaveAttribute('aria-level', '1')
  await expect(childItem).toHaveAttribute('aria-level', '2')
  await expect(leafItem).toHaveAttribute('aria-level', '3')
  await expect(rootItem).toHaveAttribute('aria-expanded', 'true')
  await tree.getByRole('button', { name: `折叠${names.root}` }).click()
  await expect(rootItem).toHaveAttribute('aria-expanded', 'false')
  await expect(childItem).toBeHidden()
  await tree.getByRole('button', { name: `展开${names.root}` }).click()
  await expect(childItem).toBeVisible()
  await page.getByRole('textbox', { name: '搜索分类' }).fill(names.leaf)
  await expect(rootItem).toBeVisible()
  await expect(leafItem).toBeVisible()
  await page.getByRole('textbox', { name: '搜索分类' }).fill('')
  await rootItem.focus()
  await rootItem.press('ArrowDown')
  await expect(childItem).toBeFocused()
  await rootItem.click()
  await expect(page.getByLabel('分类详情')).toContainText(`当前分类：${names.root}`)
  await page.getByRole('button', { name: `更多操作：${names.root}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认操作', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('引用')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await expect(rootItem).toBeVisible()
})
